# Generated by Django 4.2 on 2025-06-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0002_alter_cattle_owner_alter_testresult_cattle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="dummy_field",
            field=models.CharField(default="test", max_length=10),
        ),
    ]
