# Generated by Django 4.2 on 2025-06-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0003_testresult_dummy_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testresult",
            name="dummy_field",
        ),
    ]
