services:
  - type: web
    name: cattle-disease-detection
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cattle_disease.wsgi_render:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: cattle-disease-db
          property: connectionString

databases:
  - name: cattle-disease-db
    databaseName: cattle_disease_db
    user: cattle_user
